### ISSUE TITLE
How to understand the statement: 'normally increase the maintenance costs of a test case.'?

### ISSUE THREAD

**Issue by lugreen** [cuba-platform/guides#79]
Hi @mariodavid ,

I'm translating the article:  [Middleware Integration Testing in CUBA Applications](https://github.com/cuba-platform/guides/blob/master/_posts/2020-03-10-integration-testing-middleware.adoc).

There is a statement that i can't understand, could you explain what it means?

```
This option is also a state verification. Generally, it is preferable to use the state verification, as those verifications are usually more robust and normally increase the maintenance costs of a test case.
```
Do you mean " state verification" will  increase the maintenance costs of a test case ?

**Comment by mariodavid** [comment]
Hi,

I think it is just wrong :)

What I meant was that it will be better to do state verification from a maintenance point of view over doing very heavy mock verifications, because it is generally a more stable API and therefore is less likely to change...

Let me think about a proper phrase for it.

**Comment by lugreen** [comment]
ok, i see,will  translate by your said. Thank you.

**Comment by mariodavid** [comment]
see: https://github.com/cuba-platform/guides/pull/80

**Comment by mariodavid** [comment]
@lugreen I pushed the changes. You can take another look if you want. Thanks for noticing!

Cheers
Mario
